nohup: ignoring input
INFO:     Will watch for changes in these directories: ['/home/finance/rate_bot']
INFO:     Uvicorn running on http://0.0.0.0:8081 (Press CTRL+C to quit)
INFO:     Started reloader process [798060] using StatReload
INFO:     Started server process [798063]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     147.92.150.193:0 - "POST /callback HTTP/1.1" 200 OK
INFO:     147.92.150.195:0 - "POST /callback HTTP/1.1" 200 OK
INFO:     147.92.150.195:0 - "POST /callback HTTP/1.1" 200 OK
INFO:     147.92.150.195:0 - "POST /callback HTTP/1.1" 200 OK
INFO:     147.92.150.195:0 - "POST /callback HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/finance/rate_bot/line_bot.py", line 27, in callback
    handler.handle(body.decode("utf-8"), signature)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/linebot/webhook.py", line 278, in handle
    self.__invoke_func(func, event, payload)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/linebot/webhook.py", line 290, in __invoke_func
    func(event)
  File "/home/finance/rate_bot/line_bot.py", line 38, in handle_message
    reply_text = rate.main(f"{event.message.text}")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/finance/rate_bot/get_rate.py", line 28, in main
    self.data = self.data[f'{curr.upper()}']
                ~~~~~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: 'JOY'
INFO:     147.92.150.195:0 - "POST /callback HTTP/1.1" 200 OK
INFO:     147.92.150.195:0 - "POST /callback HTTP/1.1" 200 OK
INFO:     147.92.150.195:0 - "POST /callback HTTP/1.1" 200 OK
INFO:     147.92.149.166:0 - "POST /callback HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/finance/rate_bot/line_bot.py", line 27, in callback
    handler.handle(body.decode("utf-8"), signature)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/linebot/webhook.py", line 278, in handle
    self.__invoke_func(func, event, payload)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/linebot/webhook.py", line 290, in __invoke_func
    func(event)
  File "/home/finance/rate_bot/line_bot.py", line 38, in handle_message
    reply_text = rate.main(f"{event.message.text}")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/finance/rate_bot/get_rate.py", line 28, in main
    self.data = self.data[f'{curr.upper()}']
                ~~~~~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: 'JPY '
INFO:     147.92.149.166:0 - "POST /callback HTTP/1.1" 200 OK
INFO:     147.92.149.166:0 - "POST /callback HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/finance/rate_bot/line_bot.py", line 27, in callback
    handler.handle(body.decode("utf-8"), signature)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/linebot/webhook.py", line 278, in handle
    self.__invoke_func(func, event, payload)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/linebot/webhook.py", line 290, in __invoke_func
    func(event)
  File "/home/finance/rate_bot/line_bot.py", line 38, in handle_message
    reply_text = rate.main(f"{event.message.text}")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/finance/rate_bot/get_rate.py", line 28, in main
    self.data = self.data[f'{curr.upper()}']
                ~~~~~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: 'JPY '
INFO:     147.92.150.195:0 - "POST /callback HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/finance/rate_bot/line_bot.py", line 27, in callback
    handler.handle(body.decode("utf-8"), signature)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/linebot/webhook.py", line 278, in handle
    self.__invoke_func(func, event, payload)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/linebot/webhook.py", line 290, in __invoke_func
    func(event)
  File "/home/finance/rate_bot/line_bot.py", line 38, in handle_message
    reply_text = rate.main(f"{event.message.text}")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/finance/rate_bot/get_rate.py", line 28, in main
    self.data = self.data[f'{curr.upper()}']
                ~~~~~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: 'JOY'
INFO:     147.92.149.166:0 - "POST /callback HTTP/1.1" 200 OK
INFO:     147.92.150.195:0 - "POST /callback HTTP/1.1" 200 OK
INFO:     147.92.150.195:0 - "POST /callback HTTP/1.1" 200 OK
INFO:     147.92.149.166:0 - "POST /callback HTTP/1.1" 200 OK
INFO:     147.92.149.166:0 - "POST /callback HTTP/1.1" 200 OK
INFO:     147.92.150.195:0 - "POST /callback HTTP/1.1" 200 OK
INFO:     147.92.150.195:0 - "POST /callback HTTP/1.1" 200 OK
INFO:     147.92.150.195:0 - "POST /callback HTTP/1.1" 200 OK
INFO:     147.92.150.195:0 - "POST /callback HTTP/1.1" 200 OK
INFO:     147.92.150.195:0 - "POST /callback HTTP/1.1" 200 OK
INFO:     147.92.150.195:0 - "POST /callback HTTP/1.1" 200 OK
INFO:     147.92.150.195:0 - "POST /callback HTTP/1.1" 200 OK
INFO:     147.92.149.167:0 - "POST /callback HTTP/1.1" 200 OK
INFO:     147.92.149.167:0 - "POST /callback HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/finance/rate_bot/line_bot.py", line 27, in callback
    handler.handle(body.decode("utf-8"), signature)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/linebot/webhook.py", line 278, in handle
    self.__invoke_func(func, event, payload)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/linebot/webhook.py", line 290, in __invoke_func
    func(event)
  File "/home/finance/rate_bot/line_bot.py", line 38, in handle_message
    reply_text = rate.main(f"{event.message.text}")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/finance/rate_bot/get_rate.py", line 28, in main
    self.data = self.data[f'{curr.upper()}']
                ~~~~~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: 'JOY'
INFO:     147.92.149.167:0 - "POST /callback HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/finance/rate_bot/line_bot.py", line 27, in callback
    handler.handle(body.decode("utf-8"), signature)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/linebot/webhook.py", line 278, in handle
    self.__invoke_func(func, event, payload)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/linebot/webhook.py", line 290, in __invoke_func
    func(event)
  File "/home/finance/rate_bot/line_bot.py", line 38, in handle_message
    reply_text = rate.main(f"{event.message.text}")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/finance/rate_bot/get_rate.py", line 28, in main
    self.data = self.data[f'{curr.upper()}']
                ~~~~~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: 'JOY'
INFO:     147.92.149.167:0 - "POST /callback HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/finance/rate_bot/line_bot.py", line 27, in callback
    handler.handle(body.decode("utf-8"), signature)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/linebot/webhook.py", line 278, in handle
    self.__invoke_func(func, event, payload)
  File "/home/finance/miniconda3/envs/rate_bot/lib/python3.11/site-packages/linebot/webhook.py", line 290, in __invoke_func
    func(event)
  File "/home/finance/rate_bot/line_bot.py", line 38, in handle_message
    reply_text = rate.main(f"{event.message.text}")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/finance/rate_bot/get_rate.py", line 28, in main
    self.data = self.data[f'{curr.upper()}']
                ~~~~~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: 'JPY '
INFO:     147.92.149.167:0 - "POST /callback HTTP/1.1" 200 OK
INFO:     147.92.150.195:0 - "POST /callback HTTP/1.1" 200 OK
INFO:     147.92.150.195:0 - "POST /callback HTTP/1.1" 200 OK
INFO:     147.92.150.195:0 - "POST /callback HTTP/1.1" 200 OK
INFO:     147.92.150.195:0 - "POST /callback HTTP/1.1" 200 OK
INFO:     147.92.150.195:0 - "POST /callback HTTP/1.1" 200 OK
